"""Red-team a real trading bot from its own saved outputs (no re-running its code, no touching its live account).

Reads the bot's daily equity curves (one column per variant, at 1x and 5x costs) and applies the audits that
need only returns and disclosed variants: PSR, Deflated Sharpe under several assumed trial counts, cost
stress (its own 5x-cost run), and forward-test power. The re-run attacks (delay, placebo, holdout) would need
the bot's engine, so they are listed as not done.

Output goes to private/ (gitignored): the bot belongs to a separate project and is not published here.
Usage: .venv/Scripts/python.exe scripts/trader_case_study.py <path-to-trader-repo>
"""

from __future__ import annotations

import csv
import json
import sys
from math import erf, sqrt
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from qrt.stats import annual_sharpe, expected_max_sr, moments, psr, sharpe, t_stat  # noqa: E402

RUNS = {
    "holdout-etf-v21-008": "Holdout test, 21 never-used ETFs, 2005-2024",
    "final-exam-2025-qqq-v21": "Final exam, QQQ, 2025-01 to 2026-10 (used once)",
}
VARIANTS = {  # column prefix -> plain name
    "frozen": "Bot, frozen (the deployed version)",
    "learned": "Bot, with learning",
    "universe_frozen": "Bot, frozen, whole ETF universe",
    "universe_learned": "Bot, learning, whole ETF universe",
    "buy_hold": "Buy and hold",
    "universe_equal_weight": "Equal-weight buy and hold",
}
ASSUMED_TRIALS = (10, 50, 120)
Z95, Z80 = 1.6448536, 0.8416212


def read_curves(path: Path) -> dict[str, np.ndarray]:
    with open(path, newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    return {k: np.array([float(r[k]) for r in rows]) for k in rows[0] if k != "date"}


def excess_returns(cols, prefix):
    eq = cols.get(f"{prefix}_equity")
    if eq is None:
        return None
    r = eq[1:] / eq[:-1] - 1
    return r - cols["rf"][1:]


def audit(r: np.ndarray) -> dict:
    n, sr = len(r), sharpe(r)
    skew, kurt = moments(r)
    ann = annual_sharpe(r)
    out = {"days": n, "years": round(n / 252, 2), "sharpe": round(ann, 2), "t": round(t_stat(r), 2),
           "psr": round(psr(sr, n, skew, kurt), 3)}
    for k in ASSUMED_TRIALS:
        out[f"dsr_{k}"] = round(psr(sr, n, skew, kurt, sr_star=expected_max_sr(k, 1.0 / n)), 3)
    if ann > 0:
        out["years_for_80pct_power"] = round(((Z95 + Z80) / ann) ** 2, 1)
        out["pass_chance_1y_paper"] = round(0.5 * (1 + erf((ann - Z95) / sqrt(2))), 3)
    return out


def main() -> None:
    trader = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT.parent / "adaptive-trader"
    result = {}
    for run, title in RUNS.items():
        c1 = read_curves(trader / "runs" / run / "curves-cost1.csv")
        c5 = read_curves(trader / "runs" / run / "curves-cost5.csv")
        rows = {}
        for prefix, name in VARIANTS.items():
            r1, r5 = excess_returns(c1, prefix), excess_returns(c5, prefix)
            if r1 is None:
                continue
            a = audit(r1)
            a["sharpe_cost5"] = round(annual_sharpe(r5), 2) if r5 is not None else None
            a["t_cost5"] = round(t_stat(r5), 2) if r5 is not None else None
            rows[prefix] = {"name": name, **a}
        result[run] = {"title": title, "variants": rows}

    out_dir = ROOT / "private"
    out_dir.mkdir(exist_ok=True)
    (out_dir / "trader-case-study.json").write_text(json.dumps(result, indent=1))
    lines = ["# Red-teaming the trading bot (private)", "",
             "Generated by `scripts/trader_case_study.py` from the bot's saved equity curves. Sharpe ratios are on",
             "returns in excess of the risk-free rate. **Not published**: the bot belongs to a separate project.", ""]
    for run, block in result.items():
        lines += [f"## {block['title']}", "",
                  "| Variant | Years | Sharpe | t | PSR | DSR (10 / 50 / 120 trials) | Sharpe at 5x costs | Years of paper trading for 80% power |",
                  "|---|---|---|---|---|---|---|---|"]
        for v in block["variants"].values():
            lines.append(f"| {v['name']} | {v['years']} | {v['sharpe']:+.2f} | {v['t']:+.2f} | {v['psr']:.2f} | "
                         f"{v['dsr_10']:.2f} / {v['dsr_50']:.2f} / {v['dsr_120']:.2f} | "
                         f"{v['sharpe_cost5'] if v['sharpe_cost5'] is not None else '–'} | {v.get('years_for_80pct_power', '–')} |")
        lines.append("")
    lines += ["Re-run attacks (delay, placebo, holdout) were **not** run: they need the bot's engine, and its live",
              "paper account must not be disturbed.", ""]
    (out_dir / "trader-case-study.md").write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
